export const mutationOwnership = {
  createIngredient: 'ingredient',
  updateIngredient: 'ingredient',
  transitionIngredientTrackingMode: 'ingredient',
  createInventory: 'inventory',
  consumeInventory: 'inventory',
  disposeExpiredInventory: 'inventory',
  snoozeInventoryExpiryAlerts: 'inventory',
  correctInventoryExpiryDate: 'inventory',
  upsertInventoryState: 'inventory',
  snoozeStateExpiryAlert: 'inventory',
  correctStateExpiryDate: 'inventory',
  setInventoryStateAbsent: 'inventory',
  submitShoppingIntake: 'inventory',
  submitInventoryReconciliation: 'inventory',
  revertInventoryOperation: 'inventory',
  createShopping: 'shopping',
  updateShopping: 'shopping',
  deleteShopping: 'shopping',
  createRecipe: 'recipe',
  updateRecipe: 'recipe',
  deleteRecipe: 'recipe',
  cookRecipe: 'recipe',
  previewCookRecipe: 'recipe',
  createFoodPlanItem: 'food-plan',
  updateFoodPlanItem: 'food-plan',
  deleteFoodPlanItem: 'food-plan',
  createFoodScene: 'food-plan',
  updateFoodScene: 'food-plan',
  deleteFoodScene: 'food-plan',
  createFood: 'food',
  updateFood: 'food',
  toggleFavorite: 'food',
  updateMeal: 'meal',
  recordMeal: 'meal',
  updateMealComposition: 'meal',
  revertMealRecord: 'meal',
  completeFoodPlanItem: 'meal',
  updateConversationVisibility: 'ai-conversation',
  deleteConversation: 'ai-conversation',
} as const;

export type AppMutationName = keyof typeof mutationOwnership;
