from __future__ import annotations

PENDING = "pending"
RUNNING = "running"
COMPLETED = "completed"
FAILED = "failed"
CANCELLED = "cancelled"
WAITING_APPROVAL = "waiting_approval"
WAITING_INPUT = "waiting_input"

RUN_STATUS_PENDING = PENDING
RUN_STATUS_RUNNING = RUNNING
RUN_STATUS_COMPLETED = COMPLETED
RUN_STATUS_FAILED = FAILED
RUN_STATUS_CANCELLED = CANCELLED
RUN_STATUS_WAITING_APPROVAL = WAITING_APPROVAL
RUN_STATUS_WAITING_INPUT = WAITING_INPUT

TERMINAL_RUN_STATUSES = {COMPLETED, FAILED, CANCELLED}
WAITING_RUN_STATUSES = {WAITING_APPROVAL, WAITING_INPUT}
