from __future__ import annotations

PENDING = "pending"
RUNNING = "running"
COMPLETED = "completed"
FAILED = "failed"
FALLBACK = "fallback"
CANCELLING = "cancelling"
CANCELLED = "cancelled"
WAITING_APPROVAL = "waiting_approval"
WAITING_INPUT = "waiting_input"

RUN_STATUS_PENDING = PENDING
RUN_STATUS_RUNNING = RUNNING
RUN_STATUS_COMPLETED = COMPLETED
RUN_STATUS_FAILED = FAILED
RUN_STATUS_FALLBACK = FALLBACK
RUN_STATUS_CANCELLING = CANCELLING
RUN_STATUS_CANCELLED = CANCELLED
RUN_STATUS_WAITING_APPROVAL = WAITING_APPROVAL
RUN_STATUS_WAITING_INPUT = WAITING_INPUT

ACTIVE_RUN_STATUSES = {PENDING, RUNNING, WAITING_APPROVAL, WAITING_INPUT, CANCELLING}
TERMINAL_RUN_STATUSES = {COMPLETED, FAILED, FALLBACK, CANCELLED}
WAITING_RUN_STATUSES = {WAITING_APPROVAL, WAITING_INPUT}
