export const queryKeys = {
  authMe: ['auth', 'me'] as const,
  family: ['family'] as const,
  members: ['members'] as const,
  ingredients: ['ingredients'] as const,
  inventory: ['inventory'] as const,
  shoppingList: ['shopping-list'] as const,
  recipes: ['recipes'] as const,
  recipeDiscovery: ['recipe-discovery'] as const,
  recipeStats: ['recipe-stats'] as const,
  recipeFavorites: ['recipe-favorites'] as const,
  foodPlanRoot: ['food-plan'] as const,
  foodPlan: (start: string, end: string) => ['food-plan', start, end] as const,
  foodScenes: ['food-scenes'] as const,
  foods: ['foods'] as const,
  foodRecommendations: ['food-recommendations'] as const,
  mealLogs: ['meal-logs'] as const,
  activityLogs: ['activity-logs'] as const,
  aiStatus: ['ai-status'] as const,
  aiConversations: ['ai-conversations'] as const,
  aiMessages: (conversationId: string | null) => ['ai-messages', conversationId] as const,
  aiPendingApprovals: (conversationId: string | null) => ['ai-pending-approvals', conversationId] as const,
};
