/** Meal contracts. Keep this barrel type-only so domain imports add no runtime chunk. */
export type {
  CreateFoodPlanItemPayload,
  DeductionSuggestion,
  Food,
  FoodType,
  FoodPlanItem,
  FoodRecommendationItem,
  FoodRecommendations,
  MealFoodEntry,
  MealInsight,
  MealInsightEvidence,
  MealInsightFood,
  MealInsightKind,
  MealLog,
  MealLogCandidate,
  MealLogCandidateFood,
  MealLogRecordOperation,
  MealLogRecordOperationFoodSummary,
  MealLogRecordOperationSummary,
  MealLogRecordStatus,
  MealType,
  MediaAsset,
  Member,
  RecordMealEntryPayload,
  RecordMealNewFoodPayload,
  RecordMealPayload,
  RecordMealPlanCompletionPayload,
  RecordMealResponse,
  RecordMealTarget,
  RevertMealRecordResponse,
  UpdateFoodPayload,
  UpdateMealCompositionPayload,
  UpdateMealLogPayload,
} from '../types';
