import { FoodWorkspaceEditorOverlay } from './FoodWorkspaceEditorOverlay';
import { FoodWorkspaceRecipeEditorOverlay } from './FoodWorkspaceRecipeEditorOverlay';

export function FoodWorkspaceEditorSurface({ context: c }: { context: any }) {
  const editor = { open: c.view !== 'list' && !c.isFoodRecipeEditorOpen, title: c.view === 'create' ? '新增食物' : '编辑食物', description: c.isSelfMade ? '家常菜的菜谱、用料和日常记录都可以在这里补充。' : '补充来源、价格、评分和到期信息，方便下次继续安排。', isSavingFood: Boolean(c.props.isSavingFood), isPhoneViewport: Boolean(c.props.isPhoneViewport), completedCount: c.editorCompletedCount, onClose: c.closeFoodEditorIfAllowed, onSubmit: (e: any) => void c.handleSubmitFood(e), editor: { ...c.editorView, formId: c.FOOD_EDITOR_FORM_ID, form: c.form, imageState: c.imageComposer.state, isSavingFood: c.props.isSavingFood, isSceneTagPickerOpen: c.isSceneTagPickerOpen, isSelfMade: c.isSelfMade, isUpdatingScene: c.props.isUpdatingScene, newSceneTagName: c.newSceneTagName, sceneTags: c.editorSceneTags, submitLabel: c.foodEditorSubmitLabel, view: c.view, onFormChange: c.setForm, onGenerateImage: (m: any) => void c.imageComposer.generate(m), onResetImage: c.imageComposer.reset, onSceneTagPickerToggle: () => c.setIsSceneTagPickerOpen((v: boolean) => !v), resolveAssetUrl: c.resolveFoodAssetUrl, setNewSceneTagName: c.editorView.setNewSceneTagName } };
  const r = c.recipeEditor;
  const recipe = { dialog: { currentRecipeTitle: c.currentRecipe?.title, isEditing: Boolean(r.selectedRecipeId || c.form.recipeId), isSaving: Boolean(c.props.isCreatingRecipe || c.props.isUpdatingRecipe), onClose: c.closeFoodRecipeEditor }, view: { ...c.recipeView, form: r.form, setForm: r.setForm, ingredientRows: r.ingredientRows, ingredients: c.props.ingredients, sceneTagDraft: r.sceneTagDraft, setSceneTagDraft: r.setSceneTagDraft, sceneSelectOptions: c.recipeEditorSceneSelectOptions, editorSceneTags: c.recipeEditorSceneTags, visibleStepTips: r.visibleStepTips, editorCoverUrl: c.recipeEditorCoverUrl, editorCoverAsset: c.recipeEditorCoverAsset, editorIngredientCount: c.recipeEditorIngredientCount, editorStepCount: c.recipeEditorStepCount, editorCompletionItems: c.recipeEditorCompletionItems, editorCompletionPercent: c.recipeEditorCompletionPercent, recipeDraftError: r.recipeDraftError, recipeImageState: c.recipeEditorImageComposer.state, submitDisabled: c.recipeEditorSubmitDisabled, isCreatingRecipe: c.props.isCreatingRecipe, isUpdatingRecipe: c.props.isUpdatingRecipe, onSubmit: (e: any) => void c.submitFoodRecipeEditor(e), onBack: c.closeFoodRecipeEditorIfAllowed, updateIngredientRow: r.updateIngredientRow, selectIngredientRow: r.selectIngredientRow, updateIngredientNote: r.updateIngredientNote, updateIngredientRequirement: r.updateIngredientRequirement, addIngredientRow: r.addIngredientRow, removeIngredientRow: r.removeIngredientRow, updateStepDraft: r.updateStepDraft, getStepKeyPointValues: r.getStepKeyPointValues, getStepKeyPointRowCount: r.getStepKeyPointRowCount, addStepTip: r.addStepTip, addStepKeyPoint: r.addStepKeyPoint, updateStepKeyPoint: r.updateStepKeyPoint, removeStepKeyPoint: r.removeStepKeyPoint, commitSceneTagDraft: r.commitSceneTagDraft, handleRecipeImageUpload: (f: any) => c.recipeEditorImageComposer.upload(f), handleRecipeImageGenerate: (m: any) => c.recipeEditorImageComposer.generate(m), resetRecipeImageInput: c.recipeEditorImageComposer.reset } };
  return <><FoodWorkspaceEditorOverlay {...editor} />{c.isFoodRecipeEditorOpen && <FoodWorkspaceRecipeEditorOverlay {...recipe} />}</>;
}
