import { FoodWorkspaceMealOverlays } from './FoodWorkspaceMealOverlays';
import { FoodWorkspaceDialogController } from './FoodWorkspaceDialogController';
import { FoodWorkspacePlanOverlays } from './FoodWorkspacePlanOverlays';
import { MealEnrichmentModal } from '../../features/meals/MealEnrichmentModal';

export function FoodWorkspaceOperationalOverlays({ c }: { c: any }) {
  return <>
    <FoodWorkspaceMealOverlays resultBar={{ result: c.props.recordResult ?? null, isReverting: c.props.isRevertingRecord, revertError: c.props.recordRevertError, rateError: c.props.recordRateError, onRevert: c.props.onRevertRecord, onView: c.props.onViewRecord, onRate: c.props.onRateRecord, onDismiss: c.props.onDismissRecord }} quickRecord={{ record: c.quickRecord, recipes: c.props.recipes, dateOptions: c.quickMealDateOptions, isRecording: c.props.isQuickAdding, setRecord: c.setQuickRecord, onSubmit: () => void c.submitCompactRecord() }} quickMeal={c.quickMealDialog ? { dialog: c.quickMealDialog, dateOptions: c.quickMealDateOptions, isQuickAdding: c.props.isQuickAdding, isUpdatingPlan: c.props.isUpdatingPlan, recipes: c.props.recipes, onChange: c.updateQuickMealDialog, onClose: () => c.setQuickMealDialog(null), onSubmit: c.submitCookConfirmDialog } : null} />
    <FoodWorkspaceDialogController detail={{ food: c.detailFood, recipes: c.props.recipes, mealLogs: c.props.mealLogs, recipeCards: c.recipeCards, todayDate: c.todayDate, isQuickAdding: c.props.isQuickAdding, onClose: c.closeDetail, onEdit: c.handleOpenEdit, onEditRecipe: c.handleOpenRecipeEditorDirectly, onOpenPlanDialog: c.openPlanDialog, onStartCook: () => { if (c.detailFood) c.openQuickMealDialog(c.detailFood, c.getDefaultMealType(c.detailFood), 'cook'); }, onQuickAdd: (food: any, mealType: any) => c.openQuickMealDialog(food, mealType, 'eat'), resolveAssetUrl: c.resolveFoodAssetUrl }} />
    <FoodWorkspacePlanOverlays planDialog={{ isOpen: c.isPlanDialogOpen, selectedPlanFood: c.selectedPlanFood, foods: c.props.foods, recipes: c.props.recipes, planFoodSearch: c.planFoodSearch, planForm: c.planForm, todayDate: c.todayDate, isUpdatingPlan: c.props.isUpdatingPlan, onClose: c.closePlanDialog, onSubmit: c.submitPlanItem, onClearPlanFoodSelection: c.clearPlanFoodSelection, onPlanFoodSearchChange: c.setPlanFoodSearch, onSelectPlanFood: (food: any) => { c.setPlanForm((current: any) => ({ ...current, foodId: food.id, mealType: c.getDefaultMealType(food) })); c.setPlanFoodSearch(food.name); }, onPlanDateChange: (value: any) => c.setPlanForm({ ...c.planForm, planDate: value }), onMealTypeChange: (value: any) => c.setPlanForm({ ...c.planForm, mealType: value }), onPlanNoteChange: (value: any) => c.setPlanForm({ ...c.planForm, note: value }), resolveFoodAssetUrl: c.resolveFoodAssetUrl, getFoodCover: c.getFoodCover, getFoodCoverAsset: c.getFoodCoverAsset, getDefaultMealType: c.getDefaultMealType, getPlanDateParts: c.getFoodPlanDateParts, normalizeFoodType: c.normalizeFoodType }} planDetail={c.activePlanDetailItem ? { item: c.activePlanDetailItem, food: c.activePlanDetailFood, recipes: c.props.recipes, form: c.planDetailForm, isEditing: c.isPlanDetailEditing, isUpdatingPlan: c.props.isUpdatingPlan, isCompleting: Boolean(c.props.isCompletingPlan || c.props.isQuickAdding), onClose: c.closePlanDetail, onChangeForm: c.setPlanDetailForm, onEditingChange: c.setIsPlanDetailEditing, onResetEdit: c.resetPlanDetailForm, onSubmit: c.submitPlanDetail, completePlanItem: (target: any) => void c.completePlanItem(c.activePlanDetailItem, target), deletePlanItem: () => void c.deletePlanDetail(c.activePlanDetailItem), resolveAssetUrl: c.resolveFoodAssetUrl } : null} />
    <MealEnrichmentModal open={Boolean(c.planMealEnrichment)} meal={c.planMealEnrichment?.meal ?? null} members={c.props.members} isUpdating={Boolean(c.props.isUpdatingMeal)} updateMealLog={c.props.updateMealLog} onClose={() => c.setPlanMealEnrichment(null)} overlayRootClassName="food-workspace-overlay-root" formId="food-plan-meal-enrichment-form" />
    <FoodWorkspaceDialogController detail={undefined} scenes={{ isSceneManagerOpen: c.isSceneManagerOpen, sceneFormMode: c.sceneFormMode, sceneCards: c.sceneCards, sceneDraft: c.sceneDraft, sceneImageState: c.sceneImageState, isUpdatingScene: c.props.isUpdatingScene, onCloseManager: () => c.setIsSceneManagerOpen(false), onOpenCreateScene: () => c.openCreateScene(), onOpenEditScene: c.openEditScene, onDeleteScene: (id: string) => void c.deleteScene(id), onCloseSceneForm: c.closeSceneForm, onSubmitScene: c.submitScene, onGenerateSceneImage: () => void c.generateFoodSceneImage(), onSceneDraftChange: c.setSceneDraft, resolveFoodAssetUrl: c.resolveFoodAssetUrl }} />
  </>;
}
